USE db_leave;
START TRANSACTION;
UPDATE approvals	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE approvals	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE departments	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE departments	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE failed_jobs	failed_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	approved_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	hr_notified_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	manager_approved_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	supervisor_approved_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE leave_requests	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE notifications	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE notifications	read_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE notifications	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE password_reset_tokens	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE permissions	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE permissions	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE roles	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE roles	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE users	created_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE users	email_verified_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
UPDATE users	updated_at SET
   = CASE WHEN  IS NOT NULL THEN DATE_ADD(, INTERVAL 7 HOUR) ELSE NULL END;
COMMIT;

